### ISSUE TITLE
After exporting it everything is a mess (3d Model looks so small!)

### ISSUE THREAD

**Issue by uzublecker** [DarklightGames/io_export_psk_psa#11]
Hi. After exporting my modified mesh it looks weird, after import it back it looks too small in comparation to the retail model. The images go in this way (left to right)

Preview in blender from my modified model, preview in MilkShape 3D (exported), preview in MilkShape 3D (Retail) then there are two comparations, where the most small is the exported with your addon (Blue wireframes in MilkShape 3D are supposed to be bones, the skeleton in general. Apparently if it is small and where the root bone is like the retail who have it where the arm start is correct).

Hope this can be patched or be told if something I'm doing wrong. 

Thanks in advance
Uzublecker

![Mesh (modified with new knife) NOT JOINTED - connected by bones](https://user-images.githubusercontent.com/92300155/150075901-ab1a3791-e5f3-46fd-a507-8064189cfd8a.png)
![Milkshape preview (Exported)](https://user-images.githubusercontent.com/92300155/150075908-0f0e87f8-c383-465e-a303-1b466ce7edeb.png)
![MilkShape preview (Retail model)](https://user-images.githubusercontent.com/92300155/150075938-a0cd502b-047c-49ad-8292-262852cf2181.png)
![Preview between retail (left) and exported (right)](https://user-images.githubusercontent.com/92300155/150075960-b7af01bb-95ed-42f5-9fca-b500970728e1.png)
![Preview 2 - exported it's very small](https://user-images.githubusercontent.com/92300155/150075971-f1f8699d-a46f-4476-a0dc-dd0eb74f997c.png)

**Comment by cmbasnett** [comment]
How are you importing the model into Blender in the first place? This addon does not yet provide PSK import functionality (though it is coming later this week).

I suspect you may be using this addon for import: https://github.com/Befzz/blender3d_import_psk_psa. It has the unfortunate default functionality of scaling down models on import which might be the cause of the troubles. Please let me know if this is the case.

**Comment by uzublecker** [comment]
Yes, I a using that addon of Befzz. Hmm as I see in your reply you'll drop an import functionality soon this week. I will wait to see if the result change. Befzz's addon was the one most closed import function to last blender versions (I am using 2.9)
