### ISSUE TITLE
Cannot export static object

### ISSUE THREAD

**Issue by mirh** [DarklightGames/io_export_psk_psa#2]
Or at least, I suppose that's the only special thing about this mesh that may cause a "must have one armature modifier" error. 

[Source file](https://github.com/DarklightGames/io_export_psk_psa/files/4570432/ice20_sideofficeroof.pskx.zip)

**Comment by cmbasnett** [comment]
I will add support for exporting a "static mesh", it will just automatically add a bone if there are no modifiers.

**Comment by cmbasnett** [comment]
@mirh This functionality has been added and will be available in the next release (will publish one within the week).
