### ISSUE TITLE
UDK doesn't display exported mesh

### ISSUE THREAD

**Issue by mirh** [DarklightGames/io_export_psk_psa#3]
[Sample](https://github.com/DarklightGames/io_export_psk_psa/files/4570502/HMF_ARM_CTHb_MDL.psk.zip)
`Import in blender > export from blender > import in udk` has something broken in between.

**Comment by mirh** [comment]
Ok, I found out this is due to the "scale down" option in Befzz's plugin (the model is there, it's just minuscule). 
But I'm not sure if this is actually on him or you (i.e. to add a "scale up" option) https://github.com/Befzz/blender3d_import_psk_psa/pull/43

**Comment by cmbasnett** [comment]
It's advised to simply scale the models appropriately before exporting.

**Comment by mirh** [comment]
Can't you have the default checkbox state be disabled?
Or have it to remember the last setting?

**Comment by cmbasnett** [comment]
Presumably you are referring to the "scale down" option on the _importer_. This repository does not manage the importer. This repository is for the exporter add-on.

**Comment by mirh** [comment]
Sorry, brain fart, I had inverted who was doing what. 
As I said last year, I'm not sure if the "scale down" option is actually 100% legit (in the sense that it has actual use cases, therefore it should have an equivalent here too), or if it's rather just a random quirk that exists because [somebody](https://github.com/Befzz/blender3d_import_psk_psa/issues/38) was just too lazy to zoom out every time.
