### ISSUE TITLE
Having issues installing this into Blender 2.83 

### ISSUE THREAD

**Issue by GitHubCrazy1** [DarklightGames/io_export_psk_psa#4]
Hello Colin,

I seem to be having issues installing this into 2.83. It does not show up in my addons folder?

Can you please advise? I tried installing the  io_export_psk_psa-master.zip file, but it seems to be not showing up in the addons screen nor does the init file. 

Thanks.

**Comment by Padme4000** [comment]
I know this is late but in case runs into the issue you can put the contents of the zip directly into your addons folder. So for me it is C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\addons and then it worked

**Comment by cmbasnett** [comment]
Installation instructions have been added that should make it clear how to properly install the add-on.
