### ISSUE TITLE
ActorX

### ISSUE THREAD

**Issue by Lasercar** [DarklightGames/io_export_psk_psa#8]
I'm wondering if it's possible to port/recreate ActorX for blender, and if not, then copy over some of the options/features used for export.

Source code: [github ActorX](https://github.com/gildor2/ActorX ) 
It's under a BSD-3 Clause License.

**Comment by cmbasnett** [comment]
What kind of functionality specifically would you want ported over? I don't have access to 3DS or Maya so I can't view what kind of things it can do.

**Comment by Lasercar** [comment]
https://docs.unrealengine.com/udk/Two/ActorXMaxTutorial.html
![ActorX Setup](https://user-images.githubusercontent.com/64717068/132447507-d27cdfd8-8640-4e9b-a39a-e47f07471ff2.png) (Image of the setup since they didn't put one there)

This should help. I don't quite know what functionality would be useful. 

The different way of exporting animations could be an option. They have their range specified, are given a name and "digested" for export. It persists between files too.

**Comment by cmbasnett** [comment]
To be perfectly honest, most of these settings have are either undesirable (to me) or have no relevance to the way that Blender does things. For example, why *wouldn't* you want the smoothing groups to be exported?

As for the animations, it would be nice, I suppose, to have some sort of persistence to list of animations to be exported. This is, however, a very niche request that I'm not really convinced is all that necessary, and certainly not one I would use personally. The plugin already automatically selects actions for export that have f-curves for bones corresponding to the armature you're trying to export animations from. The PSA exporter also allows you choose (with an actual interface) which animations to export in a PSA.

![image](https://user-images.githubusercontent.com/5035660/132595613-796ad05e-f218-4ecd-8291-6adc51300e6a.png)

If you can come up with a practical, real-world use-case for any of the features you like ActorX, I encourage you to open a new ticket and explain how you'd like it to work in this plugin. In the meantime though, I'm going to close this ticket as it's too open-ended, and simply recreating ActorX is not something I'm interested in doing.
